# Generated by Django 4.2.4 on 2023-08-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskId',
            field=models.IntegerField(default=0),
        ),
    ]
