# Generated by Django 4.2.4 on 2023-08-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_taskmodel_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.TextField(max_length=500),
        ),
    ]
